apiVersion: batch/v1
kind: CronJob
metadata:
  name: post-install
  annotations:
    argocd.argoproj.io/sync-wave: "28"
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}      
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: openshift4/ose-tools-rhel8:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |
                set -e
                if oc get secret sonarqube-root-token -n {{ .Release.Namespace }} ; then
                    echo "sonarqube-root-token is already created exiting..."
                else
                    echo "sonarqube-root-token doesn't exist"
                    echo "creating token..."
                    export token=$(curl -s -u admin:admin1 -X POST -H "Content-Type: application/json" https://{{ include "sonarqube.fullname" . }}-{{ .Release.Namespace }}.apps.{{ .Values.base_domain }}/api/user_tokens/generate?name=backstage | jq -r .token)
                    echo "creating sonarqube-root-token secret..."
                    oc create secret generic sonarqube-root-token -n {{ .Release.Namespace }} --from-literal=token=${token}
                fi    
            
          restartPolicy: OnFailure