kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'edit-privileges'
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}    
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'edit'   