kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: sonarqube
  labels:
    {{- include "soranqube.labels" . | nindent 4 }}    
spec:
  host: host: {{ include "sonarqube.fullname" . }}.apps.{{ .Values.base_domain }}
  to:
    kind: Service
    name: sonarqube
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
