apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: sonarqube-credential-config
spec:
  labelSelector:
    matchLabels:
      environment: build
  templates:  
    - objectTemplate: |      
        apiVersion: v1
        kind: Secret
        metadata:
          name: sonarqube-credentials
          namespace: {{ .Name }}
          annotations:
            reflector.v1.k8s.emberstack.com/reflects: "sonarqube/sonarqube-credentials"
            reflector.v1.k8s.emberstack.com/reflected-version: ""   