kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'ctlog-nonroot'
  namespace: ctlog-system
  labels:
    {{- include "sigstore.labels" . | nindent 4 }}  
subjects:
  - kind: ServiceAccount
    name: ctlog-createtree
    namespace: ctlog-system
  - kind: ServiceAccount
    name: sigstore-ctlog-createctconfig
    namespace: ctlog-system
  - kind: ServiceAccount
    name: ctlog
    namespace: ctlog-system          
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:nonroot-v2'


