apiVersion: batch/v1
kind: CronJob
metadata:
  name: transit-ci-system-init
  namespace: vault-admin
  annotations:
    argocd.argoproj.io/sync-wave: "28"
  labels:
    {{- include "sigstore.labels" . | nindent 4 }}      
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject-token: "true"
            vault.hashicorp.com/role: "policy-admin"
            vault.hashicorp.com/tls-skip-verify: "true"
            vault.hashicorp.com/agent-init-first: "true"
        spec:
          initContainers:
          - name: check-existance-of-transit-path
            image: registry.connect.redhat.com/hashicorp/vault:1.12.0-ubi
            imagePullPolicy: IfNotPresent
            env:  
            - name: VAULT_ADDR
              value: https://vault.vault.svc:8200
            - name: VAULT_SKIP_VERIFY
              value: "true"
            command:
            - /bin/bash
            - -c
            - |
                set -e
                set -u
                set -x
                set -o pipefail
                export VAULT_TOKEN=$(cat /vault/secrets/token)
                vault list -format=yaml transit/keys | grep ci-system | wc -l > /shared/result
            volumeMounts:
            - name: shared
              mountPath: /shared                 
          containers:
          - name: hello
            image: docker.io/bitnami/cosign:latest
            imagePullPolicy: IfNotPresent
            env:  
            - name: VAULT_ADDR
              value: https://vault.vault.svc:8200
            - name: VAULT_SKIP_VERIFY
              value: "true"            
            command:
            - /bin/bash
            - -c
            - |
                set -e
                set -u
                set -x
                set -o pipefail
                export VAULT_TOKEN=$(cat /vault/secrets/token)
                export count=$(cat ./shared/result)
                if [ ${count} -eq 0 ] then 
                  cosign generate-key-pair --kms hashivault://ci-system
                fi
            volumeMounts:
            - name: shared
              mountPath: /shared             
          restartPolicy: OnFailure
          volumes:
            - name: shared
              emptyDir: {}          