kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'tuf-anyuid'
  namespace: tuf-system
  labels:
    {{- include "sigstore.labels" . | nindent 4 }}  
subjects:
  - kind: ServiceAccount
    name: tuf
    namespace: tuf-system      
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'

  oc adm policy add-scc-to-user anyuid -z tuf -n tuf-system