apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-configuration
  namespace: openshift-gitops
  labels:
    {{- include "argo-applications.labels" . | nindent 4 }} 
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "25"    
spec:
  project: default
  source:
    repoURL: {{ .Values.gitRepo.URL }}
    targetRevision: {{ .Values.gitRepo.targetRevision }}
    path: vault-configuration
    directory:
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-admin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
  ignoreDifferences:
  - group: redhatcop.redhat.io
    kind: GitHubSecretEngineConfig
    name: github
    namespace: vault-admin
    jsonPointers:
    - /spec/applicationID
    - /spec/organizationName
  - group: redhatcop.redhat.io
    kind: Policy
    name: database-engine-admin
    namespace: vault-admin
    jsonPointers:
    - /spec/policy      