apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: ${gitRepoURL}
    path: argo-applications/argo-applications
    targetRevision: ${gitRepoRevision}
    helm:
      values: | 
        baseDomain: ${baseDomain}      
        gitRepo: 
          URL: ${gitRepoURL}
          targetRevision: ${gitRepoRevision}
        git: 
          organization: ${organization}  
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true       
    retry:
      limit: 0 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
  ignoreDifferences:
  - group: ""
    kind: Secret
    namespace: openshift-gitops
    name: kcp-secret
    jsonPointers:
    - /data/config
  - group: argoproj.io
    kind: Application
    namespace: openshift-gitops
    name: user-workload-grafana
    jsonPointers:
    - /spec/source/helm/values         

    