apiVersion: redhatcop.redhat.io/v1alpha1
kind: KubernetesAuthEngineRole
metadata:
  name: ci-system
spec:
  # Add fields here
  authentication: 
    path: kubernetes
    role: policy-admin
  path: kubernetes  
  policies:
    - ci-system
  targetServiceAccounts:
  - pipeline  
  targetNamespaces:
    targetNamespaceSelector:
      matchExpressions:
        - key: team
          operator: Exists
        - key: environment
          operator: In
          values:
          - build