apiVersion: v1
kind: ConfigMap
metadata:
  name: chains-config
  namespace: openshift-pipelines
  labels:
    {{- include "openshift-pipelines-configurations.labels" . | nindent 4 }}  
data:
  artifacts.oci.format: simplesigning
  artifacts.oci.signer: x509
  artifacts.oci.storage: oci,tekton

  artifacts.taskrun.format: in-toto
  artifacts.taskrun.storage: oci,tekton
  artifacts.taskrun.signer: x509

  artifacts.pipelinerun.format: in-toto
  artifacts.pipelinerun.storage: oci,tekton
  artifacts.pipelinerun.signer: x509

  transparency.enabled: "true"
  transparency.url: https://rekor.apps.{{ .Values.baseDomain }}
  #signers.kms.kmsref: hashivault://ci-system
  #signers.kms.auth.address: https://vault.apps.{{ .Values.baseDomain }}				
  #signers.kms.auth.oidc.path: kubernetes	
  #signers.kms.auth.oidc.role: vault-admin