kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "argo-rollouts.fullname" . }}
  labels:
    {{- include "argo-rollouts.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "argo-rollouts.fullname" . }}-dashboard
    weight: 100
  port:
    targetPort: 3100
  tls:
    termination: edge
  wildcardPolicy: None